[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }
data = { path = "../data" }

async-recursion = "1.1.1"
anyhow = "1.0.86"
indexmap = "2.4.0"

tokio = { version = "1.39.3", features = ["rt", "sync", "time"] }
parking_lot = "0.12.3"
