{
  parserClass="bigbade.raven.ravenintellijplugin.parsing.RavenParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Raven"
  psiImplClassSuffix="Impl"
  psiPackage="bigbade.raven.ravenintellijplugin.psi"
  psiImplPackage="bigbade.raven.ravenintellijplugin.psi.impl"

  elementTypeHolderClass="bigbade.raven.ravenintellijplugin.psi.RavenTypes"
  elementTypeClass="bigbade.raven.ravenintellijplugin.parsing.RavenElementType"
  tokenTypeClass="bigbade.raven.ravenintellijplugin.parsing.RavenTokenType"

  tokens = [
    STRUCT="struct"
    FUNC = "fn"
    RBRACKET = "}"
    LBRACKET = "{"
    RPAREN = ")"
    LPAREN = "("
    COLON = ":"
    SEMICOLON = ";"
    space='regexp:\s+'
    number='regexp:\d+(\.\d*)?'
    ident='regexp:\p{Alpha}\w*'
  ]
}

ravenFile ::= item_*

private item_ ::= (structure|elem_)

modifier ::= "pub " | "static "
structure ::= modifier* STRUCT LBRACKET elem_* RBRACKET

private elem_ ::= (function|struct_field)

struct_field ::= modifier* ident COLON ident SEMICOLON

function ::= modifier* FUNC LPAREN RPAREN code

code ::= LBRACKET expr_* RBRACKET

private expr_ ::= effect_ SEMICOLON

private effect_ ::= ()
